## Decision Tree for Iris FLower Multi-class Classification

### Import libs

In [1]:
import numpy as np
import pandas as pd

### Load Data

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
iris.target.shape

(150,)

In [7]:
iris.data.shape

(150, 4)

In [8]:
uniq, count = np.unique(iris.target, return_counts=True)
print(uniq,count)


[0 1 2] [50 50 50]


### Make data ready

In [9]:
X = iris.data
y = iris.target

In [10]:
X.shape

(150, 4)

## Decision Tree Model

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40, random_state=42)

In [12]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

### Prediction

In [14]:
pred = dtree.predict(X_test)

### Evaluation

In [15]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score

In [16]:
print(classification_report(y_test, pred))
print('ConfusionMatrix:\n',confusion_matrix(y_test, pred))
print('\nAcuracy: {0:.2f}\n' .format(accuracy_score(y_test, pred)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       0.95      0.95      0.95        19
           2       0.94      0.94      0.94        18

   micro avg       0.97      0.97      0.97        60
   macro avg       0.96      0.96      0.96        60
weighted avg       0.97      0.97      0.97        60

ConfusionMatrix:
 [[23  0  0]
 [ 0 18  1]
 [ 0  1 17]]

Acuracy: 0.97

